---
- name: 1.2.4
  hosts: all
  become: yes 
  tasks: 
    - name: Check whether 
      script: subs.sh
      register: checkmyconf
      check_mode: no
      ignore_errors: yes
      changed_when: no

    - name: Greet the world if /tmp/my.conf contains 
      debug: msg="machine has valid subscription"
      when: checkmyconf.rc == 0
